[build]
  command = "npm run build:frontend"
  publish = "dist/public"
  
[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_URL = "https://trynex-gift-shop-1.onrender.com"

[context.deploy-preview.environment]
  VITE_API_URL = "https://trynex-gift-shop-1.onrender.com"