
services:
  - type: web
    name: trynex-backend
    env: node
    plan: free
    buildCommand: npm ci --include=dev && npm run build:backend
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: postgresql://postgres.wifsqonbnfmwtqvupqbk:Amits@12345@aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres
